" Install vim-plug if not present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Plugins used
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'               " Sensible defaults for vim
call plug#end()

" Force vim to use english
language en_US
set langmenu=en_US

" General editor settings
set number                              " show line numbers
set linebreak                           " break lines at words
set showbreak=+++                       " Prefix for wrapped lines
set textwidth=80                        " Number of cols 
set visualbell                          " Use visual bell (no beeping here, mister)
set modeline                            " Enable modelines
set modelines=5                         " Check the first 5 rows for modelines

" Indents
set autoindent                          " Auto-indent new lines
set expandtab                           " Use spaces instead of tabs
set shiftwidth=4                        " Number of auto-indent spaces
set smartindent                         " Enable smart-indent
set smarttab                            " Enable smart-tabs
set softtabstop=4                       " Use 4 spaces per tab

" Search
set hlsearch                            " highlight all search results
set smartcase                           " Enambe smart-case search
set ignorecase                          " Be case-insensitive
set incsearch                           " Do incremental search

